### ISSUE TITLE
Na ordenação dos pesquisadores a ordem alfabética considera todas as maiúsculas e depois minúsculas

### ISSUE THREAD

**Issue by alexsandroccarv** [unifesp/prodmais#15]
A ordenação não deveria ser Juliana **de** Lima junto com a Juliana D***

![Captura de tela de 2023-05-31 20-29-22](https://github.com/unifesp/prodmais/assets/658734/386c24f9-cc4a-4bbf-a437-1dbe498f42e2)

**Comment by trmurakami** [comment]
Corrigido
